### PR TITLE
redundant code

### PR DESCRIPTION
**Pull request by monsieuralok**
redundant code. Please check as it get crashed during DEBUG.

### CODE REVIEW

**Comment by MichaelSchulzMETNO** [comment]
@monsieuralok The description is not clear. Is the "redundant" code needed to avoid crashes on tetralith?

**Comment by monsieuralok** [comment]
@MichaelSchulzMETNO it is required on all machines as some variables are not initialised and some of this code is not used anywhere.

**Comment by DirkOlivie** [comment]
I will do a test on vilje to see whether these changes keep the results bit-identical.

**Comment by DirkOlivie** [comment]
The code modification does not affect simulations on vilje (I tested NF1850norbc compset).  So fine for me.

**Pull request merged**
