### PR TITLE
noresm2_5_015_cam6_4_041: Updates from ESCOMP/CAM

### LINKED ISSUE #173: Update CAM with new NCAR configurations
- Update ESCOMP/CAM from cam6_3_158 to 6_4_041
- Improvements to the CAM7 physics
- Changes to the way wet deposition is implemented
- New input data set
- New way to handle ndep emissions to CTSM

### PR DESCRIPTION
**Pull request by gold2718**
Summary: Update CAM with  ESCOMP changes between cam6_3_158 and cam6_4_041

Contributors: gold2718

Reviewers: DirkOlivie, mvertens, oyvindseland

Purpose of changes:  Update CAM with new NCAR configurations #173

Github PR URL: https://github.com/NorESMhub/CAM/pull/175

Changes made to build system: Replace manage_externals with git-fleximod

Changes made to the namelist:
- CAM3 entries removed
- New entries for gravity wave moving mountain parameterization
- GEOSchem updates
- RRTMGP added as a radiation scheme
- New SCAM variables
- Wetdep variables made into independent namelist
- New (temporary?) dust emission variables to coordinate with CTSM

Changes to the defaults for the boundary datasets: None (for LT)

Substantial timing or memory changes: None

Change highlights:
- Adjustments to chemistry compset names
- Bring in re-organized atmospheric_physics repo
- Update to GEOS-Chem 14.4.3 and HEMCO 3.9.0, and add Cloud-J 7.7.3 and HETP 1.0
- Generalize aerosol wet removal
- Add missing total energy in physics state from dycore in snapshots and cleanup total water
- Use same cloud water for radiation and COSP.
- fix psl values sent to coupler in cam7
- Updates to age of air diagnostic tracers
- Add capability to use Leung dust emission scheme
- Repartition dust deposition fluxes passed to surface models
- Deposition fixes for aquaplanet and simple model configurations.
- SCAM-SE feature addition plus bugfixes and some refactoring
- Remove 0.5*timestep from call to ZM
- Correction to aerosol convective removal
- New CLUBB external
- Add climate-chemistry compset
- Initial Gravity Wave moving mountain
- replaced outdated log-gamma function with intrinsic
- fix clubb interface bug (dry/moist mixing ratio conversion)
- Limit vertical domain used by COSP.
- activate additional clubb diffusion in cam6
- Change name of physics package 'cam_dev' to 'cam7'
- Replace manage_externals with git-fleximod
- Update subcomponents where ESCOMP component is used directly in CAM
- Update top level externals to match NorESMhub/NorESM/noresm_develop
- Diagnostic rainbows
- New PUMAS external with fixed GPU directives

closes #173

### CODE REVIEW

**Comment by oyvindseland** [comment]
I think I will have a hard time going through all the namelist updates. I presume that at least a couple of the modified compsets have been tested, ideally from a clean clone?

Some questions: 
As far as I can see there are no updates to the NorESM / oslo_aero specific files or shadow files --> Most NorESM compsets will not work within this update? Or are the shadow files complete enough that it can still use old code?
Same question for PUMAS
All the binary object files being added back and forth / deleted etc. Are these really needed as commits?
Minor detail: Although  cam3 is,  supposed to be? removed I notice it is still included in bld/config_files/definition.xml

**Comment by gold2718** [comment]
> All the binary object files being added back and forth / deleted etc. Are these really needed as commits?

Good question. These are due to the replacement of manage_externals (136 files including several binary files) with git-fleximod (30 files). Is that what you were referring to?

**Comment by gold2718** [comment]
> Minor detail: Although cam3 is, supposed to be? removed I notice it is still included in bld/config_files/definition.xml

Good catch! This is an oversight on my part. I will remove it.

**Comment by oyvindseland** [comment]
> > All the binary object files being added back and forth / deleted etc. Are these really needed as commits?
> 
> Good question. These are due to the replacement of manage_externals (136 files including several binary files) with git-fleximod >(30 files). Is that what you were referring to?

Yes these are the files. I thought that at least some of those files comes from the files add to your local repo and is changed for every new checkout to your local repo. I never thought it was needed to add files such as .gitignore upstream?

**Review by DirkOlivie — APPROVED** [review]
Hi Steve, I went fast through all the files in a clone on Betzy (instead of on Github).  It was only a very quick scan - but I did not notice anything strange.  Best regards, Dirk

**Review by oyvindseland — APPROVED** [review]
I just had a brief look through all the files and was not able to see any problems (except for the CAM3 text)

**Pull request merged**
