### PR TITLE
KeyClim Cloud2 tunings

### PR DESCRIPTION
**Pull request by gold2718**
Summary: Make KeyClim Cloud2 tunings the default for NFHIST and HF1850

Contributors: gold2718, oyvindseland

Reviewers: DirkOlivie, oyvindseland 

Purpose of changes: Prepare compsets to use KeyClim Cloud2 tunings as the default

Github PR URL: https://github.com/NorESMhub/CAM/pull/142

Changes made to build system: None

Changes made to the namelist: Added new namelist items to allow for new tuning parameters
- hetfrz_aer_scalfac: Scaling factor for aerosols
- clubb_meltpt_temp: Temperature used for the melting temp of ice crystals [K]
- clubb_dt_low: Temperature at which detrained water is classified as entirely ice (no liquid) in the CLUBB parameterization in units of (K).

Changes to the defaults for the boundary datasets: None

Substantial timing or memory changes: None

- Import int2str from noresm_develop branch
- Make meltpt_temp and dt_low run-time parameters for CLUBB - Defaults are 268.15 and 238.15 - NorESM defaults are 243.15 and 238.15
- Add namelist definitions, defaults and exceptions for clubb_meltpt_temp and clubb_dt_low
- Add new option, CLOUD2, for keyClim simulations
- Make the KeyClim cloud2 tunings the default, move old settings to usermods

Test suite aux_cam_noresm runs with the expected namelist and baseline changes

Issues addressed by this PR: Create new compsets for NorESM2.3, NorESMhub/NorESM#465

### CODE REVIEW

**Review by DirkOlivie — APPROVED** [review]
Hi Steve, seems fine for me.  Best regards, Dirk

**Review by oyvindseland — APPROVED** [review]
The changes look fine. One question: The purely cosmetic changes in some of the files, typically removal of empty characters at the end of the line. Is that on purpose or is it caused by using different editing tools?

**Comment by gold2718** [comment]
> One question: The purely cosmetic changes in some of the files, typically removal of empty characters at the end of the line. Is that on purpose or is it caused by using different editing tools?

I have all my editors set to automatically remove spaces at the end of each line when saving a file. This is the practice we adopted at NCAR to (eventually) lower the number of spurious changes presented in a PR. Note that when reviewing a PR, you can always hide these whitespace changes. Just below the "Files changed" tab is a gear icon. Clicking on that reveals a "Hide whitespace" checkbox which will hide those changes for easier reviewing. I plan to continue this practice as I edit files since many have accumulated a lot of these extra spaces over the years. Let me know if that is a problem or if you would like to also adopt the practice.

**Comment by oyvindseland** [comment]
OK. No problems with the practice

**Pull request merged**
