### PR TITLE
pass 10m u,v from cam to mediator that will then be send to ww3

### PR DESCRIPTION
**Pull request by mvertens**
Add new 10m wind fields to be sent from cam to mediator and then to ww3dev

noresm_develop: Add new 10m wind fields to be sent from cam to mediator and then to ww3dev. This will need accompanying PRs in CMEPS and in WW3DEV

Summary: Add new 10m wind fields to be sent from cam to mediator and then to ww3dev

Contributors: mvertens

Reviewers: @gold2718 gold2718

Changes made to build system: None

Changes made to the namelist: None

Changes to the defaults for the boundary datasets: None

Substantial timing or memory changes: None

Issues resolved: #136 

Testing: 
Simulations with ww3dev were run with this new change and the results improved.
Ran aux_cam_noresm test suite. Results were bfb with baseline noresm_v9_cam6_3_123/ (except for new fields) and new baseline noresm_v10_cam6_3_123 was generated. 

Dependencies: This PR depends on the following PRs being **merged first**:
https://github.com/NorESMhub/CAM-Nor-physics/pull/10
https://github.com/NorESMhub/CMEPS/pull/16

### CODE REVIEW

**Review by gold2718 — APPROVED** [review]
Looks good!

**Comment by mvertens** [comment]
@gold2718 - I think this can be merged at this point.

**Comment by gold2718** [comment]
> Simulations with ww3dev were run with this new change and the results improved.

Was any test run that does not make use of these fields?

**Comment by mvertens** [comment]
@gold2718 - no test was run that does not make use of these fields. I can wait until new baselines are generated with PR #128 and then rerun the test suite again those if you want.

**Review by gold2718 — APPROVED** [review]
:+1:

**Pull request merged**
