### PR TITLE
include sectional nucleation parameterisation as a option in CAM-Nor

### PR DESCRIPTION
**Pull request by oyvindseland**
Included the option for running the sectional nucleation parameterisation from Sara Blichner and three compsets that include the settings needed. Nudging and twin 1850 / 2014 compsets used for ERF calculations. No impact on other compsets.

### CODE REVIEW

**Comment by MichaelSchulzMETNO** [comment]
Great, this gets included. Is it possible to point to (document) to the test simulations with (non activated), with (option acitvated) and without the additional capability ?

**Comment by oyvindseland** [comment]
I have done an aerosol ERF simulation. I am running some diagnostics now but the averaging and scripts take some time to finish. Will include link to results when completed.

**Comment by oyvindseland** [comment]
The sectional approach can only be included at compset level and for now I have only tested the twin ERF compset using 1850 SST and 1850 or 2014 aerosol emissions. I have also compared the results with default settings. In general the changes are quite small except for lower particle number in the lower troposphere including near surface. 
Comparison with default: http://ns2345k.web.sigma2.no/diagnostics/noresm/oyvinds/NF1850norbc_f19_f19_nucsec_20220930/CAM_DIAG/yrs1to30-NF1850norbc_f19_f19_devdef_20220809-yrs1to30/sets.htm
Aerosol comparison with standard settings and ERF calculations: http://ns2345k.web.sigma2.no/aerosol_diagnostics/NF1850norbc_f9_f19_devstd_20220809vsNF1850norbc_f19_f19_sectionalnuc_20220930/ModIvsModII.htm

**Review by DirkOlivie — APPROVED** [review]
Ok for me.

**Pull request merged**
