### PR TITLE
noresm2_3_develop : modified SOA yield factors for isoprene

### LINKED ISSUE #154: Change yield of production of secondary organic aerosols from isoprene
### What is the feature/what would you like to discuss?

The yield of isprene to SOA should be reduced from 5 % to 0.5 % Impact all chemistry set-up (chem_mech.doc) Should likely be default in NorESM2.3. Sara Blichner should be asked if she still think the 0.5 % is what she recommends. Added her github in the discussion section below 

### Is there anyone in particular you want to be part of this conversation?

@sarambl

### Will this change (regression test) answers?

Yes

### Will you be implementing this enhancement yourself?

Yes, but I will need some help

### PR DESCRIPTION
**Pull request by DirkOlivie**
Summary: The amount of low-volatile SOA-precursor gas formed from isoprene is made smaller by a factor of 10 : the original yield of 0.05 has been lowered to a yield of 0.005. 

Contributors: This suggestion was made by @sarambl, and the pull-request was made by @DirkOlivie 

Reviewers: Sara Blichner (@sarambl), Steve Goldhaber(@gold2718), Øyvind Seland (@oyvindseland)

Purpose of changes: issue #154 (Change yield of production of secondary organic aerosols from isoprene)

Github PR URL: PR #176 (https://github.com/NorESMhub/CAM/pull/176)

Changes made to build system: None

Changes made to the namelist: None

Changes to the defaults for the boundary datasets: None

Substantial timing or memory changes: None

Detailed description of changes : 
We have updated the pp_trop_mam_oslo and the pp_tropstrat_mam_oslo chemical schemes, which in total affected 8 files (4 for every chemical scheme).  These files are : 

src/chemistry/pp_trop_mam_oslo/chem_mech.doc
src/chemistry/pp_trop_mam_oslo/chem_mech.in
src/chemistry/pp_trop_mam_oslo/mo_lin_matrix.F90
src/chemistry/pp_trop_mam_oslo/mo_prod_loss.F90

src/chemistry/pp_tropstrat_mam_oslo/chem_mech.doc
src/chemistry/pp_tropstrat_mam_oslo/chem_mech.in
src/chemistry/pp_tropstrat_mam_oslo/mo_nln_matrix.F90
src/chemistry/pp_tropstrat_mam_oslo/mo_prod_loss.F90

The F90 files have been auto-generated by running the preprocessor for the modified chemical schemes defined by chem_mech.in.  
In chem_mech.in in pp_trop_mam_oslo the modifications consisted of changing
```
isoprene + O3 -> .05*SOA_SV            ; 1.03e-14, -1995.
isoprene + OH -> .05*SOA_SV            ; 2.7e-11, 390.
isoprene + NO3 -> .05*SOA_SV           ; 3.15e-12, -450.
```
into
```
isoprene + O3 -> .005*SOA_SV           ; 1.03e-14, -1995.
isoprene + OH -> .005*SOA_SV           ; 2.7e-11, 390.
isoprene + NO3 -> .005*SOA_SV          ; 3.15e-12, -450.
```
In chem_mech.in in pp_tropstrat_mam_oslo (where a different tracer name for isoprene and slightly different reaction rates are use) the modifications consisted of changing
```
ISOP  + O3  -> ISOP  + O3  + .05*SOA_SV           ; 1.05e-14, -2000
ISOP  + OH  -> ISOP  + OH  + .05*SOA_SV           ; 2.54e-11, 410
ISOP  + NO3 -> ISOP  + NO3 + .05*SOA_SV           ; 3.03e-12, -446
```
into
```
ISOP  + O3  -> ISOP  + O3  + .005*SOA_SV           ; 1.05e-14, -2000
ISOP  + OH  -> ISOP  + OH  + .005*SOA_SV           ; 2.54e-11, 410
ISOP  + NO3 -> ISOP  + NO3 + .005*SOA_SV           ; 3.03e-12, -446
```
Testing:
test simulations have been run only for two simulated months.  The results are different, but the impact has not been analyzed in detail.  Hope to do that when starting spin-up simulations.

Issues addressed by this PR:
[#154]  (https://github.com/NorESMhub/CAM/issues/154)

resolves #154

### CODE REVIEW

**Comment by oyvindseland** [comment]
Do you know why there are differences in reaction rates? The isoprene vs ISOP is probably a NorESM1.2 vs WACCM issue.
Should perhaps be homogenized for NorESM3?

**Comment by MichaelSchulzMETNO** [comment]
> Do you know why there are differences in reaction rates? The isoprene vs ISOP is probably a NorESM1.2 vs WACCM issue. Should perhaps be homogenized for NorESM3?

I dont understand - the reaction rates are the same, just the yield is smaller.

**Comment by oyvindseland** [comment]
The new reaction rates are the same as the old ones but for some reason, as Dirk points out the reaction rates are slightly different in pp_trop_mam_oslo and pp_tropstrat_mam_oslo. I propose to accept the changes as they are now, but we should homogenize the rates in NorESM3.

**Review by gold2718 — APPROVED** [review]
This looks good.
When you get a chance, could you add something about the testing done below the files changed section?

**Pull request merged**
